version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "jgarber623"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jgarber623"
  - package-ecosystem: "npm"
    directory: "/google/cloud-functions/inbox"
    schedule:
      interval: "monthly"
    assignees:
      - "jgarber623"
