dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2
before_install:
  - gem update --system
  - gem update bundler
  - nvm install node
  - npm install -g sass-lint
notifications:
  email: false
  slack:
    rooms:
      secure: r5uPBJX4MCbxTzjDe7KwPg0egsgsVcAE9vzYku5UvvhujdTPCUuMhE2AueEXS5OajeeyKTN/+q9bzcCRKiwaOc2u/I1fCGvKlgapTKe/BwIwCWThfuk5x7FKU1pq75DOJIXoapvfD/ZmM9u2MhL8fnSNH0NmIl2EZ43UpUL7X5HX6y8Jhkhvq4QgJ6RlwKSu33SfRQapCcmY3fEVtQoI/W98ViAJv+A1CwR0B6rB6lz8s+iL/T/GJO2g3fcqEZ4Xgumkr3zFokg2ShGxVRur/lzUqJCkJcqxxW9Wf/tskDcWN3ig8houQT3gVGusCWeZJeoiDdNEMXIen1IixVGqJF0yAuS9xTVlJZSazgUkQAeKmFA216+UzPWCMKIRjBuxkyVcowIZCeRLxkCeOcssPrwj7E8U5NAolTObpHEfe2/T+EcUXD8ZQNzLxrngPnUxDs99aGLXzdgQbjJhe4IjFDKD3SRhCkrIDI3GF58uOXuGMqvNSRpRMs1mIc9HBTXKDIeqodp4lklb1cDkjVP4LSLUHv8y8huRib32zwlEIk0cSL8edZBnNQ2RWFaPOdtJ8Lc4suk84xBjArtAbZsbBg8k9X0iadGJ5CZx33fcLwNe5oBqZva2xDf0suFbaxOEe9DboPqYSYYgdkfHnnEgDt1aN66/PjKn7T4saRTc1xg=
