[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """\
      base-uri 'self'; \
      block-all-mixed-content; \
      child-src 'self' https://bandcamp.com; \
      default-src 'self'; \
      form-action 'none'; \
      frame-ancestors 'none'; \
      frame-src 'self' https://bandcamp.com; \
      img-src * data:; \
      media-src *; \
      object-src 'none'; \
      script-src 'self' 'unsafe-inline'; \
      style-src 'self' 'unsafe-inline'; \
      worker-src 'none';\
    """
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/jrd+json; charset=UTF-8"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "/users/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/activity+json; charset=UTF-8"

[[redirects]]
  from   = "https://whoistheorchid-com.netlify.app/*"
  to     = "https://whoistheorchid.com/:splat"

[[redirects]]
  from   = "/@theorchid"
  to     = "/@theorchid.html"
  status = 200
