[build]
publish = "public"
command = "bin/rake build"

[context.production.environment]
JEKYLL_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * data:; media-src *; child-src 'self' https://bandcamp.com; frame-ancestors 'none';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/biography"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * data:; media-src *; child-src 'self' https://bandcamp.com; frame-ancestors 'none';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/releases"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * data:; media-src *; child-src 'self' https://bandcamp.com; frame-ancestors 'none';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/releases/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * data:; media-src *; child-src 'self' https://bandcamp.com; frame-ancestors 'none';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/shows"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src * data:; media-src *; child-src 'self' https://bandcamp.com; frame-ancestors 'none';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/biography"
  to = "/biography/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/shows"
  to = "/shows/index.html"
  status = 200
  force = true
