source: ./src
destination: ./public

plugins:
  - breakpoint
  - jekyll-assets
  - sass-globbing

host: 0.0.0.0

permalink: /:categories/:title

defaults:
  - scope:
      path: releases
      type: posts
    values:
      layout: release
