source: ./src
destination: ./public

gems:
  - breakpoint
  - jekyll-assets
  - sass-globbing

permalink: /:categories/:title

defaults:
  - scope:
      path: releases
      type: posts
    values:
      layout: release
